export const jobs = [
  { id: 1, title: 'Frontend Developer', company: 'TechCorp', location: 'New York', description: 'Build responsive UIs using React.js and TailwindCSS.' },
  { id: 2, title: 'Backend Developer', company: 'CodeWorks', location: 'San Francisco', description: 'Develop RESTful APIs and manage databases.' },
  { id: 3, title: 'Data Analyst', company: 'DataPros', location: 'Seattle', description: 'Analyze data trends and create insightful reports.' },
  { id: 4, title: 'UI/UX Designer', company: 'CreativeStudio', location: 'Austin', description: 'Design user-centric interfaces for mobile and web.' },
  { id: 5, title: 'Project Manager', company: 'AgileSolutions', location: 'Denver', description: 'Manage teams and oversee project delivery.' },
  { id: 6, title: 'DevOps Engineer', company: 'CloudOps', location: 'Los Angeles', description: 'Optimize CI/CD pipelines and cloud infrastructure.' },
  { id: 7, title: 'Full Stack Developer', company: 'InnovateTech', location: 'Chicago', description: 'Develop end-to-end web applications.' },
  { id: 8, title: 'AI/ML Engineer', company: 'BrainWave', location: 'Boston', description: 'Build and deploy machine learning models.' },
  { id: 9, title: 'Cybersecurity Specialist', company: 'SecureNet', location: 'Phoenix', description: 'Ensure the security of digital assets.' },
  { id: 10, title: 'Mobile App Developer', company: 'AppCraft', location: 'Miami', description: 'Develop iOS and Android applications.' },
  { id: 11, title: 'Quality Assurance Tester', company: 'Testify', location: 'San Diego', description: 'Perform testing to ensure software quality.' },
  { id: 12, title: 'Content Writer', company: 'WriteHub', location: 'Atlanta', description: 'Create engaging content for blogs and websites.' },
  { id: 13, title: 'Digital Marketing Specialist', company: 'MarketWise', location: 'Dallas', description: 'Plan and execute digital marketing campaigns.' },
  { id: 14, title: 'Cloud Architect', company: 'SkyCloud', location: 'Houston', description: 'Design scalable cloud infrastructure.' },
  { id: 15, title: 'Game Developer', company: 'PlayGround', location: 'Orlando', description: 'Develop immersive gaming experiences.' },
  { id: 16, title: 'Blockchain Developer', company: 'CryptoBuild', location: 'Las Vegas', description: 'Develop blockchain-based applications.' },
  { id: 17, title: 'Technical Support Engineer', company: 'FixIt', location: 'Charlotte', description: 'Provide technical assistance to clients.' },
  { id: 18, title: 'Human Resources Manager', company: 'PeopleFirst', location: 'Raleigh', description: 'Manage HR operations and recruitments.' },
  { id: 19, title: 'Data Engineer', company: 'DataFlow', location: 'Philadelphia', description: 'Build and maintain data pipelines.' },
  { id: 20, title: 'Business Analyst', company: 'AnalyzeIt', location: 'Detroit', description: 'Bridge business needs with technical solutions.' },
  { id: 21, title: 'Network Administrator', company: 'NetSecure', location: 'Cleveland', description: 'Manage and secure corporate networks.' },
  { id: 22, title: 'E-commerce Specialist', company: 'ShopEase', location: 'Nashville', description: 'Optimize e-commerce store performance.' },
  { id: 23, title: 'AR/VR Developer', company: 'VirtualVision', location: 'Salt Lake City', description: 'Create augmented and virtual reality experiences.' },
  { id: 24, title: 'SEO Specialist', company: 'RankUp', location: 'Portland', description: 'Improve website rankings on search engines.' },
  { id: 25, title: 'Social Media Manager', company: 'BuzzFeeders', location: 'Tampa', description: 'Manage social media accounts and content.' },
  { id: 26, title: 'Graphic Designer', company: 'DesignFlow', location: 'Kansas City', description: 'Design graphics for marketing and branding.' },
  { id: 27, title: 'IT Support Specialist', company: 'HelpDesk', location: 'Cincinnati', description: 'Troubleshoot and resolve technical issues.' },
  { id: 28, title: 'Product Manager', company: 'InnovateLabs', location: 'Pittsburgh', description: 'Lead the product lifecycle from concept to launch.' },
  { id: 29, title: 'Supply Chain Manager', company: 'LogisticsPro', location: 'Indianapolis', description: 'Optimize supply chain processes.' },
  { id: 30, title: 'Finance Analyst', company: 'MoneyMatters', location: 'Columbus', description: 'Analyze financial data and create reports.' },
];

export const applications = [
  { id: 1, jobId: 1, candidate: 'John Doe', resume: 'resume1.pdf' },
  { id: 2, jobId: 2, candidate: 'Jane Smith', resume: 'resume2.pdf' },
  { id: 3, jobId: 5, candidate: 'Mike Johnson', resume: 'resume3.pdf' },
  { id: 4, jobId: 8, candidate: 'Anna Taylor', resume: 'resume4.pdf' },
  { id: 5, jobId: 12, candidate: 'Chris Lee', resume: 'resume5.pdf' },
  { id: 6, jobId: 3, candidate: 'Emily Davis', resume: 'resume6.pdf' },
  { id: 7, jobId: 4, candidate: 'Michael Brown', resume: 'resume7.pdf' },
  { id: 8, jobId: 7, candidate: 'Olivia Wilson', resume: 'resume8.pdf' },
  { id: 9, jobId: 9, candidate: 'William Jones', resume: 'resume9.pdf' },
  { id: 10, jobId: 10, candidate: 'Sophia Martinez', resume: 'resume10.pdf' },
  { id: 11, jobId: 11, candidate: 'Benjamin Taylor', resume: 'resume11.pdf' },
  { id: 12, jobId: 6, candidate: 'Isabella Garcia', resume: 'resume12.pdf' },
  { id: 13, jobId: 2, candidate: 'James Hernandez', resume: 'resume13.pdf' },
  { id: 14, jobId: 5, candidate: 'Ava Clark', resume: 'resume14.pdf' },
  { id: 15, jobId: 8, candidate: 'Liam Walker', resume: 'resume15.pdf' },

];
export const employers = [
  { id: 1, name: 'TechCorp', email: 'contact@techcorp.com', phone: '123-456-7890' },
  { id: 2, name: 'CodeWorks', email: 'hr@codeworks.com', phone: '987-654-3210' },
  { id: 3, name: 'DataPros', email: 'info@datapros.com', phone: '456-789-0123' },
  { id: 4, name: 'CreativeStudio', email: 'team@creativestudio.com', phone: '321-654-0987' },
  { id: 5, name: 'AgileSolutions', email: 'jobs@agilesolutions.com', phone: '789-123-4567' },
  // Add up to 50 employers here for matching
];